[build]
  command = "npm install && npx vite build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = "https://vrjprwoignfmgdvjsott.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyanByd29pZ25mbWdkdmpzb3R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMTMyNDgsImV4cCI6MjA4NzY4OTI0OH0.X4bCucYJ4iGQPnKhiRWBcFNtEgUSdP570ofVRBwFPPQ"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
